E-Booking/E-Booking/Controllers/AccountWebAPIController.cs
using System;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using EBooking.Models;
using System.Web.Security;
using EBooking.Utilities;
using BusinessRules;
using System.Data;
using System.Net.Mail;
using System.Configuration;
//using E_Booking.Models;

namespace EBooking.Controllers
{
    [Authorize]
    public class AccountWebAPIController : ApiController
    {
        private static int _userid = 0;
        private static int _roleid = 0;


        [AllowAnonymous]
        public dynamic LogInUser([FromBody]LoginModel model)
        {
            //Check if AntiForgeryToken is valid
            if (!Common.IsValidAntiForgeryToken(Request))
                return Request.CreateErrorResponse(HttpStatusCode.Unauthorized, "Unauthorized attempt to E-Booking server.");

            //Check if model is valid
            if (!ModelState.IsValid)
                return Request.CreateErrorResponse(HttpStatusCode.BadRequest, "Invalid data to E-Booking server.");

            if (Validateuser(model.UserName, model.Password))
            {
                //WebSecurity.Login(model.UserName, model.Password, persistCookie: model.RememberMe);
                //FormsAuthentication.SetAuthCookie(model.UserName, false);
               
                if (_roleid != 10)
                {
                    return Request.CreateResponse(HttpStatusCode.OK, "User Not Authorized");
                }

                FormsAuthentication.SetAuthCookie(_userid.ToString(), false);

                return _userid;
            }
            else
            {
                if (_userid == -1 && _roleid == -1)
                {
                    return Request.CreateResponse(HttpStatusCode.OK, "Invalid Username or Password.");
                }
                return Request.CreateResponse(HttpStatusCode.OK, false);
            }
        }

        private bool Validateuser(string username, string pasword)
        {
            RoleBased rb = new RoleBased();

            bool validate = rb.ValidateUserWeb(username, pasword, out _userid, out _roleid);

            return validate;
            //return true;
            //throw new NotImplementedException();
        }

        public dynamic LogOutUser()
        {
            //Check if AntiForgeryToken is valid
            if (!Common.IsValidAntiForgeryToken(Request))
                return Request.CreateErrorResponse(HttpStatusCode.Unauthorized, "Unauthorized attempt to E-Booking server.");

            //Check if model is valid
            if (!ModelState.IsValid)
                return Request.CreateErrorResponse(HttpStatusCode.BadRequest, "Invalid data to E-Booking server.");

            FormsAuthentication.SignOut();

            return true;
        }

        [AllowAnonymous]
        [HttpGet]
        public dynamic ValidateUserName(string username) 
         {
            clsEBooking objEbooking = new clsEBooking();
            bool userexists = objEbooking.DoUserExists(username);
            return userexists;
        }
        
        [HttpGet]
        public dynamic GetUserDetails(string userid)
        {

            //Check if AntiForgeryToken is valid
            if (!Common.IsValidAntiForgeryToken(Request))
                return Request.CreateErrorResponse(HttpStatusCode.Unauthorized, "Unauthorized attempt to E-Booking server.");

            //Check if model is valid
            if (!ModelState.IsValid)
                return Request.CreateErrorResponse(HttpStatusCode.BadRequest, "Invalid data to E-Booking server.");

            clsEBooking objEBooking = new clsEBooking();
            DataSet ds = objEBooking.GetUserDetails(Convert.ToInt32(userid));
            if (ds.Tables[0].Rows.Count > 0)
            {
                RequestertModel _requester = new RequestertModel();
                _requester.Id = Convert.ToInt32(ds.Tables[0].Rows[0]["UserID"]);
                _requester.RequestDate = System.DateTime.Now;//.ToString("dd/MM/yyyy");//_//DateTime.Parse(System.DateTime.Now.ToString("dd/MM/yyyy"), new CultureInfo("ur-pk", false));
                _requester.GenderTitleId = Convert.ToInt32(ds.Tables[0].Rows[0]["GenderID"]);
                _requester.FirstName = ds.Tables[0].Rows[0]["FirstName"].ToString();
                _requester.Surname = ds.Tables[0].Rows[0]["SurName"].ToString();
                _requester.StaffPosition = ds.Tables[0].Rows[0]["PositionName"].ToString();
                _requester.DepartmentId = ds.Tables[0].Rows[0]["DepartmentID"].ToString();
                _requester.ServiceTypeId = ds.Tables[0].Rows[0]["ServiceID"].ToString();
                _requester.CostCentre = "";//; ds.Tables[0].Rows[0]["SurName"].ToString();
                _requester.SubjectiveCode = "";// ds.Tables[0].Rows[0]["SurName"].ToString();
                _requester.EmailAddress = ds.Tables[0].Rows[0]["Email"].ToString();
                _requester.PostalAddress = ds.Tables[0].Rows[0]["PostalAddress"].ToString();
                _requester.FacilityId = ds.Tables[0].Rows[0]["FacilityID"].ToString().Trim();
                
                _requester.ContactTelNo = ds.Tables[0].Rows[0]["TelephoneNo"].ToString().Trim();// ds.Tables[0].Rows[0]["SurName"].ToString();
                _requester.AuthorisingClinician = "";// ds.Tables[0].Rows[0]["SurName"].ToString();
                _requester.AuthorisingRoleId = "";// ds.Tables[0].Rows[0]["SurName"].ToString();
                _requester.FacilityName = ds.Tables[0].Rows[0]["FacilityName"].ToString().Trim();
                _requester.DepartmentName = ds.Tables[0].Rows[0]["FacilityDepartmentName"].ToString().Trim();
                _requester.facilityType = ds.Tables[0].Rows[0]["FacilityTypeName"].ToString().Trim();
                _requester.Extension = ds.Tables[0].Rows[0]["Extension"].ToString().Trim();


                return _requester;



            }


            return true;
        }

        [AllowAnonymous]
        public dynamic SaveUserDetails([FromBody]SignupModel model)
        {
            //Check if AntiForgeryToken is valid
            if (!Common.IsValidAntiForgeryToken(Request))
                return Request.CreateErrorResponse(HttpStatusCode.Unauthorized, "Unauthorized attempt to E-Booking server.");

            //Check if model is valid
            if (!ModelState.IsValid)
                return Request.CreateErrorResponse(HttpStatusCode.BadRequest, "Invalid data to E-Booking server.");

            clsEBooking objEBooking = new clsEBooking();
            try
            {

                objEBooking.AddorUpdateWebUser(model.FirstName, model.Username, model.Password, model.EmailAddress, model.Id, true, false, model.Position, model.GenderTitleId, model.FirstName, model.Surname, model.DepartmentId, model.PostalAddress, model.ServiceTypeId, model.ContactTelNo, model.FacilityId,model.Extension);

            }
            catch (Exception ee)
            {
                if (ee.ToString().ToLower().Contains("login already exists"))
                {
                    return Request.CreateErrorResponse(HttpStatusCode.OK, "This Email is already registered. Please try to login, if you do not remember Password Please click on the Forgot Password link on Home Page.");
                }
                return ee.ToString();
            }
            return true;
        }
        
        [AllowAnonymous]
        public dynamic GetAddress(string FacilityId, string isFacilityDepartment)
        {
            if (!Common.IsValidAntiForgeryToken(Request))
                return Request.CreateErrorResponse(HttpStatusCode.Unauthorized, "Unauthorized attempt to E-Booking server.");

            //Check if model is valid
            if (!ModelState.IsValid)
                return Request.CreateErrorResponse(HttpStatusCode.BadRequest, "Invalid data to E-Booking server.");

            try
            {

                BLFacilityAddress fa = new BLFacilityAddress();
                return fa.GetFacilityAddress(Convert.ToInt32(FacilityId), Convert.ToBoolean(isFacilityDepartment));

                //return fa.FullAddress;
                // string Address=
            }
            catch (Exception ee)
            {
                return ee.ToString();
            }

            //return true;
        }

        [AllowAnonymous]
        [HttpGet]
        public dynamic ValidateandSendEmail(string EmailAddress)
        {
            clsEBooking objEbooking = new clsEBooking();
            string _userName = "";
            string _password = "";
            if (objEbooking.CheckEmailAddress(EmailAddress,out _userName,out _password))
            {
                MailMessage mail = new MailMessage();
                mail.To.Add(EmailAddress);
               // mail.To.Add("mufassar.rashid@my.web.pk");
                mail.From = new MailAddress(ConfigurationManager.AppSettings["JourneyDetailPDFEmailFrom"]);
                mail.Subject = "Your User Credentials";
                string Body = "User Name: "+_userName+"<br />Password: "+_password;
                mail.Body = Body;
                mail.IsBodyHtml = true;

                SmtpClient smtp = new SmtpClient();
                smtp.Host = ConfigurationManager.AppSettings["SmtpServerName"];
                smtp.Port = Convert.ToInt32(ConfigurationManager.AppSettings["SmtpServerPortNo"]);
                smtp.UseDefaultCredentials = false;
                smtp.Credentials = new System.Net.NetworkCredential(ConfigurationManager.AppSettings["SmtpNetworkCredentialEmail"], ConfigurationManager.AppSettings["SmtpNetworkCredentialPassword"]);
                try
                {
                    smtp.Send(mail);
                }
                catch (Exception ex)
                {

E-Booking/E-Booking/Controllers/JourneyController.cs
using EBooking.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using itextSharpPDFController;
using System.IO;
using System.Net;
using BusinessRules;
using System.Net.Mail;
using System.Configuration;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Json;
using System.Web.Script.Serialization;
using System.Data;
using EBooking.Models;

namespace EBooking.Controllers
{
    [Authorize]
    public class JourneyController : PdfViewController
    {
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Journey()
        {
            return View();
        }
        public ActionResult JourneyView()
        {
            return View();
        }

        public ActionResult TransportSelection()
        {
            return View();
        }
        public ActionResult EscortTravelling()
        {
            return View();
        }
        public ActionResult PopUp()
        {
            return View();
        }

        public ActionResult JourneyGrid()
        {
            return View();
        }

        public ActionResult JourneyPDF()
        {
           
            return View();
        }

        public ActionResult FlowChart()
        {
            return View();
        }
        public ActionResult SortableGridTest()
        {
            return View();
        }

        public bool SendPDFEmail(string refNumber)
        {
            try
            {
                string emailto = String.Empty;
                EBooking.Models.jouneyCompositePDF journey = new Journey().GetJourneyPDF(refNumber);
                /// this.GetPDF()
                /// 



                FileContentResult PDFFile = this.GetPDF("", "JourneyPDF", journey);
                MemoryStream pdfMS = new MemoryStream(PDFFile.FileContents);

                //    clsEBooking objEBooking = new clsEBooking();
                //DataSet ds1 = objEBooking.GetUserDetails(Convert.ToInt32(User.Identity.Name));
                //if (ds1.Tables[0].Rows.Count > 0)
                //{
                //    emailto = ds1.Tables[0].Rows[0]["Email"].ToString().Trim();
                //}
                emailto = journey.EmailAddress;
                //System.IO.File.WriteAllBytes(HttpContext.Server.MapPath(@"~\App_Data\Journey-EBooking.pdf"), PDFFile.FileContents);

                using (MailMessage mail = new MailMessage())
                {
                    mail.To.Add(emailto);
                    //mail.To.Add("asif_rauf@my.web.pk");
                   // mail.To.Add("qamar.nust@gmail.com");
                  //  mail.Bcc.Add("asif_rauf@my.web.pk");
                    //mail.Bcc.Add("qamar.nust@gmail.com");
                    mail.From = new MailAddress(ConfigurationManager.AppSettings["JourneyDetailPDFEmailFrom"]);
                    mail.Subject = "DO-NOT-REPLY";
                    string Body = "Journey Details - Please Find The Attachment Above.";
                    mail.Body = Body;
                    mail.IsBodyHtml = true;

                    Attachment attachedFile = new Attachment(pdfMS, new System.Net.Mime.ContentType("application/pdf"));

                    mail.Attachments.Add(attachedFile);
                    mail.Attachments.Last().ContentDisposition.FileName = "JourneyDetails.pdf";

                    using (SmtpClient smtp = new SmtpClient())
                    {
                        smtp.Host = ConfigurationManager.AppSettings["SmtpServerName"];
                        smtp.Port = Convert.ToInt32(ConfigurationManager.AppSettings["SmtpServerPortNo"]);
                        smtp.UseDefaultCredentials = false;
                        smtp.Credentials = new System.Net.NetworkCredential(ConfigurationManager.AppSettings["SmtpNetworkCredentialEmail"], ConfigurationManager.AppSettings["SmtpNetworkCredentialPassword"]);
                        try
                        {
                            smtp.Send(mail);
                        }
                        catch (Exception ee)
                        {

                        }
                        finally
                        {
                            pdfMS.Dispose();
                         
                        }
                    }
                }

                Response.StatusCode = 200;
                return true;

            }
            catch
            {
                Response.StatusCode = 400;
                return false;
            }
            
        }
    }
}

E-Booking/E-Booking/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>E-Booking</title>
    <meta name="viewport" content="width=device-width" />
    <link href="@Url.Content("~/Content/jquery-ui.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/style.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/bootstrap.css")" rel="stylesheet" type="text/css" />

    <link href="@Url.Content("~/Content/jquery.steps.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/jquery.qtip.min.css")" rel="stylesheet" type="text/css" />

    <script src="@Url.Content("~/Scripts/jquery-1.11.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/respond.js")" type="text/javascript"></script>

    <script src="@Url.Content("~/Scripts/jquery-ui-1.11.2.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.steps.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.qtip.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/KnockoutModels/Common.js")" type="text/javascript"></script>
    <script type="text/javascript">

        @functions{
             public string TokenHeaderValue()
             {
                 string cookieToken, formToken;
                 AntiForgery.GetTokens(null, out cookieToken, out formToken);
                 return cookieToken + ":" + formToken;
             }
         }

        getUserName = function (userid) {
            //alert(userid);
            //var userName;
            @if(!User.Identity.IsAuthenticated){
              Url.Action("Index", "Journey");
            }
            $.ajax({
                url: '@Url.Action("GetUserDetails", "AccountWebAPI", new { httproute = "" })',
                type: 'GET',
                contentType: "application/json; charset=utf-8",
                headers: { 'RequestVerificationToken': '@TokenHeaderValue()' },
                data: { userid: userid },
                
                success: function (result) {
                    $("#lblUserName").text(result.FirstName + ' ' + result.Surname);

                },
                error: function (jqXHR, textStatus, errorThrown) {
                    var errorMessage = '';
                    $('#message').html(jqXHR.responseText);
                    ShowErrorMessage();
                },
                complete: function () {
                   // HideProgressBar();
                }

            });
            
            
        }

    $(function () {

        HomeClick = function () {
            window.location.replace('@Url.Action("Index", "Journey")');
        }

        ErrorDialogClick = function () {
            debugger;
            if ($(".erriText").text().toLowerCase().indexOf('authorization has been denied') >= 0 || $(".erriText").text().toLowerCase().indexOf('unauthorized attempt to e-booking') >= 0)
            {
                $("#ErrorDialog").dialog("close");
                window.location.reload();
            }
            $("#ErrorDialog").dialog("close");
        }

        LogOutClick = function () {

            $.ajax({

                url: '@Url.Action("LogOutUser", "AccountWebAPI", new { httproute = "" })',

                contentType: "application/json;charset=utf-8",

                type: "POST",

                data: ko.toJSON(self.LoginUser),

                headers: { 'RequestVerificationToken': '@TokenHeaderValue()' },

                beforeSend: function (xhr) {
                    //xhr.overrideMimeType( "text/plain; charset=x-user-defined" );
                },

                success: function (result, status, xhr) {

                    if (xhr.status == 200)
                        window.location.replace('@Url.Action("Index", "Journey")');

                },
                error: function (jqXHR, textStatus, errorThrown) {
                    //debugger;
                    var errorMessage = '';
                    $('#message').html(jqXHR.responseText);
                }
            });
        };
    });
    </script>
    <style>
        .wizard > .actions > ul{padding-left:10px;}
        .wizard > .actions {text-align: left;}
    </style>
    <noscript>Please Enable JavaScript in your Brower settings for best user Experience.</noscript>
</head>
<body>
    <div id="divheader">
        <div class="blueborder">
            <div class="slider-inner">
                <div class="da-slider">
                    <a href="#" data-bind="click: HomeClick, clickBubble: false">
                        <div class="leftlogo"></div>
                    </a>
                    <div class="topheaderheading">
                        <div class="da-slide da-slide-current">
                            <h2>
                                <span class="ebookingheading">eBooking System</span>
                                <br>
                            </h2>
                            <p>
                                <span class="topbannertext">
                                    Welcome to the Isle of Wight Ambulance Service
                                    Patient Transport Services (Non-Emergency)
                                    ‘E’ Booking System
                                </span>
                            </p>
                        </div>
                    </div>
                    <div class="bannertoprightcon">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <script>getUserName(@User.Identity.Name)</script>
                            @*<script>var xyz=getUserName(@User.Identity.Name)</script>*@ 
                             <div class="bantrtitle"><a href="#" class="toprlink" data-bind="click: HomeClick, clickBubble: false">Home</a></div>
                            <div class="bantrtitle">|</div>
                            <div class="bantrtitle"><a href="#" class="toprlink" data-bind="click: LogOutClick, clickBubble: false">Log Out</a></div>
                            <div class="bantrtitle">|</div>
                            <div class="bantrtitle"><b>Welcome: &nbsp;</b><span class="welcometitle" id="lblUserName"></span>  </div>                      
                        }
                    </div>
                    <div class="rightlogo"></div>
                </div>
            </div>
        </div>
    </div>
    <div id="ErrorDialog" class="popup-bg">
        <div class="popup-headerred">
            <div class='popup-header-text'>EBOOKING</div>
        </div>
        <div class="popup-body-innder">
            <div class="pop-up-text-main" style="margin-top:5px;"><span style="font-size:20px; font-weight:bold;">SORRY! </span> an error has occurred. We apologise for any inconvenience caused.
You will be able to view any journeys requested on the home page ‘view journeys’ button’
.
                <span style="color: red; font-size: 13px;" class="erriText"></span>
                @*;left: 13px;position: absolute;top: 80px; display:none*@
            </div>
            <div class="popup-button" style="margin-left:0;" data-bind="click: ErrorDialogClick, clickBubble: false">Ok</div>
        </div>
    </div>
    <div id="ajaxLoadingBar">
        <div class="disabledBackground"></div>
        <div class="waitingContents">
            <div style="position:relative">
                <p class="waitText">
                    <strong>
                        eBooking System
                    </strong>
                    <br />
                    Please Wait
                </p>
            </div>
        </div>
    </div>
    @RenderBody()
    <footer class="footergraybar" style="">
        <div class="footergraybar">
            <div class="da-slide da-slide-current">
                <div class="footergraybartxt">&copy; @DateTime.Now.Year - E-Booking Copyright 2014 V 1.7.0004</div>
            </div>
        </div>
    </footer>
</body>

</html>